CC=arm-cortex_a15-linux-gnueabihf-g++
target = supercatrio

SRCS=$(wildcard *.cpp)
SRCS+=$(wildcard JvGame/*.cpp)
OBJS=$(patsubst %cpp,%o,$(SRCS))

INCLUDE = -I/Volumes/linuxdisk/x-tools/arm-cortex_a15-linux-gnueabihf/arm-cortex_a15-linux-gnueabihf/sysroot/usr/include/SDL2
LIB = -L/Volumes/linuxdisk/x-tools/arm-cortex_a15-linux-gnueabihf/arm-cortex_a15-linux-gnueabihf/sysroot/usr/lib -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer

all:$(OBJS)
	$(CC) $(OBJS) -o $(target) $(LIB)

%.o:%.cpp
	$(CC) -c $< -o $@  $(INCLUDE)

clean:
	rm $(OBJS) $(target) -f

